### ISSUE TITLE
Help me. cannot read .trc file

### ISSUE THREAD

**Issue by ronnifadhlillah** [bennomeier/leCroyParser#11]
Hallo mr @bennomeier and mr @JeroenvO .

Why i can read .trc file. there's any error when executing the code. Or can you give me a sample of proper .trc file?
An error sample below.
![image](https://user-images.githubusercontent.com/33772449/155975677-693ad38f-2302-4a6c-8baa-688e61e71588.png)

Thank you.
RF

**Comment by JeroenvO** [comment]
Here a TRC file from my oscilloscope:
[C1--XX--00000.trc.txt](https://github.com/bennomeier/leCroyParser/files/8160075/C1--XX--00000.trc.txt)

**Comment by JeroenvO** [comment]
Otherwise, supply your file and i'll look into it

**Comment by bennomeier** [comment]
Hi @ronnifadhlillah,

here is a link to a .trc file that should work: https://www.dropbox.com/s/4mqt8mq5ll4b9dk/C1180430_shot100000.trc?dl=0

If problems persist, and you are sure that your file is ok, you may want to try changing the endianness in the parse function from ">" to "<" - of send the file to @JeroenvO

**Comment by ronnifadhlillah** [comment]
Hallo mr @JeroenvO and mr @bennomeier .

here's my trc fil. there's something wrong with my trc file. Let me know if there's something weird.
https://drive.google.com/file/d/1XjU4lCiYG0DdS_xwLckDVO6GQmoHS-KB/view?usp=sharing

**Comment by bennomeier** [comment]
I get the same error that you do. I would suspect that the file is not formatted in the way that lecroyparser expects, which is according to the LECROY_2_2 Template (details here https://cdn.teledynelecroy.com/files/manuals/dda-rcm-e10.pdf ). Can you check your scope's manual for the formatting ot the trc file? Where / from which scope did you get the file?

**Comment by ronnifadhlillah** [comment]
Hallo mr. @bennomeier .

I got the file generated from EXFO OTDR. Have you ever any experince with that file or EXFO .trc file? or any solution to conveert my .trc file to LECROY_2_2 template or .SOR file. ?

**Comment by bennomeier** [comment]
Oh dear, that is not going to work. You have to check the manufacturer's specification (if that is available at all), and then work your way thorugh this, or find someone who is able to work through it. This is clearly beyond what lecroyparser is made for. Good luck!

**Comment by ronnifadhlillah** [comment]
Thank you mr @bennomeier and mr @JeroenvO
