### ISSUE TITLE
Data file does not get closed

### ISSUE THREAD

**Issue by schmidf** [bennomeier/leCroyParser#3]
I have noticed that the data file does not get closed after parsing has finished unless sparse is greater than zero. This is probably due to the following line being indented one level too much:

https://github.com/bennomeier/leCroyParser/blob/1b94cdd7c93ac84abc2fe7380b23a8e2aa75eb75/lecroyparser/__init__.py#L134

**Comment by bennomeier** [comment]
Thanks for reporting - this is now fixed.
